### ISSUE TITLE
focus on "stream" rather than "client"

### ISSUE THREAD

**Issue by markfisher** [projectriff/stream-client-go#4]
if we change [this type](https://github.com/projectriff/stream-client-go/blob/master/client.go#L37) from `StreamClient` to `Stream`, and the [corresponding](https://github.com/projectriff/stream-client-go/blob/master/client.go#L65) `NewStreamClient` to `NewStream` (and the package could also change from "client" to "stream"), the user experience would be more focused on each stream as opposed to constructing multiple "client" instances when interacting with multiple streams. The `Stream` type would then include the `Publish` and `Subscribe` functions, which logically feel like they _belong to_ the stream itself.

**Comment by scothis** [comment]
I'd lean towards the package being `stream`, and the struct being `Client`.

In go `stream.Stream` is an anti pattern. See https://blog.golang.org/package-names

> Avoid stutter. Since client code uses the package name as a prefix when referring to the package contents, the names for those contents need not repeat the package name. The HTTP server provided by the http package is called Server, not HTTPServer. Client code refers to this type as http.Server, so there is no ambiguity.

**Comment by markfisher** [comment]
thanks @scothis - maybe the package should be "client" and the type should be `Stream` since the part I find odd is the creation of multiple "client" instances to interact with multiple _streams_.

**Comment by ericbottard** [comment]
To clarify, the struct members and ctor args would remain exactly the same, right? It's just that it currently feels weird that a single "Client" can't cope with multiple streams?

**Comment by markfisher** [comment]
yes @ericbottard, in fact I think the current struct members and ctor args also seem to describe the "stream" rather than a "client"

**Comment by scothis** [comment]
> it currently feels weird that a single "Client" can't cope with multiple streams

What would it mean for a single client to interact with multiple streams? Do we get any benefit?
